spring:
  application:
    name: Test
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8080
  servlet:
    session:
      timeout: 1h
    context-path: /api
  compression:
    enabled: true
    #min-response-size: 10KB
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml

security:
  encrypt:
    mode: rsa
    rsa:
      private-key: 'MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC6MrX0Qokyna6FwvhEoAuj1AuLNTtGa/ZslFB4DueTUUHdi9KMHglbFe99J14QKLZwL87u3Y6NMMdFfDOMcCzMdGWDn0KzKyX8GX5M87R/xrnICP5HKDL+uGBFkdibeCAX5wtQBc+Agkr/QxZN/+R8AP+Z8wgnJHABIKVoCafx3oCh41o1nshLicJLL/aUoXhBYDesxgzIjV+p02e3LlN7YyNp19wSUcLKSOeP4r5WEzWf8t4djDQ0P+v4KI9Jd6EBOb/yGtF0FvjXo9I5QnN5UxwMkjsKhhBXVOPzGVbo+OhRjdzOH1NzGbn3rOyqq/B6FfKvRIqMhnwQEd+3xbs5AgMBAAECggEAHc4BPzSpVn9UENhJOl7uDg7ivClMsDSW8QF6sgUcv4GZy/dWQBSMxdZIjB2Rmn+R2Hpmoui3KVWeCDrd24SXPzEAkOWc3SYygdyo0XOPOIbcdS8vWL+QDiMAUhKK/DPp2zmiH3CWqwjwLVUVTG4CKnFUeNWkv/M+tId/wpwNFJOVISZgRPqeD2Lm65JaCA87h1fWLkT9CMqL1z5IzRXmpP9GCk8CHJfHUJO25JU+UxWwj1daCRrAVaOIFgesftoq+H4xvIzNegXObNajWSA+yYqV6RHAa5/HXLgtJlsPP/CkMaNgnhNEKbtUoGHP3g6AO/t9g1gJNUx1/nFeANA2OwKBgQD79kDkla651uMsXnY9ifXlvGhwU3JGQ23v1jH+KJgJiSydoqg7Ib5bL8HjePqmDuosPQfxK8Z9S4h8QHMjpNqbNodRtNY+Oka9pat38bPyiCnbpOcYLH1AL/O0HaMOrSevrNZgZbm2oez9RqZVCEIZrskPL/F54/HXW66RTGXgQwKBgQC9LqRjp8xal9EAuafO+FAL71HQJ+UQTtYXHVY5uu9E1hDqpV/c+x7eyqMkJdaDw+uiln7iV6Xh2U8uYIKjHEgnOFLWngmBxQzZgZ69e80fvN5Y/9qjDzngL8kZIEOxLczmDobLscR5Oa5O9UU0VFnyEJ+2cPMsDhGXiqNBez5M0wKBgH4r2F8fHXnuQ6BKRUeXuE0sxdfJ0aWhyoGZbztotInB6VeexkOmKB6dkagJQuq4+Ubh4QJB+4lus5AU7hNhUB79dVHTDp3mrNn3BiBwJr5CtUNKFncigC4OVSlS1f5Zc1Ajas6m4hK0j2pdYJmgIwmdXw194pw5Kze+r3IPIczlAoGADMPG58p8qWgw/AGK5xYuIIAHXyox9IW9QFYEaWTJnDVtcsexzjFLhfDaTSgYb0+a6J+K9C7BzJljFFgCuIrB+5N7U2vabF0lXs+2LEbcMlYGEq9Ay1vNpejTgtSAfMYAW02Dnt7hyOQxdLZr8vn2D7U7cY3xenmAil8aYOK1820CgYA1FJN1H1r9zdpvU1XYn+2G4IPgE/zT5xPyzWVB2TkIsPaNDCmznAVPsbi8Qau9sFQBp0rmDug8bVFdmHVpaQk7IxkprGI3XOrAZrvLI6gfVpLHdkLbwy4LHWyrYIM93EoJddL+iOln84R092pLc+Qz6jPBWpJvrzNrzUTUGhPIUg=='
    aes:
      key: 'dBV5Awv8Ji6kIE/QledA1+MHnF3up8ur'
      iv: 'kYw1hVScyQOV2LO/'
    charset: UTF-8    # 字符类型默认UTF-8
    in-decode: true    # 默认请求参数解密
    out-encode: true   # 默认响应参数加密
    show-log: true     # 默认打印请求参数、响应参数解密加密前后的数据
